language: python
# command to install dependencies
install:
  - pip install -r requirements.txt
  - pip install coverage codecov
# command to run tests
script:
  - coverage run -m unittest
after_success:
  - codecov
